os:
  - linux
language: java
before_install: 
  - ./install_latest_gauge.sh /tmp >/dev/null 2>&1
  - source ~/.profile
  - gauge --install java
  - wget https://bintray.com/artifact/download/gauge/activeadmin-demo/activeadmin-demo.war
  - nohup java -jar activeadmin-demo.war >/dev/null 2>&1 &
  - sleep 30
  - sudo apt-get install unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - chmod +x ~/Downloads/chromedriver
  - sudo mv -f ~/Downloads/chromedriver /usr/bin/chromedriver
  - export DISPLAY="0:0"
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo apt-get install xvfb
  - Xvfb :0 -ac -screen 0 1024x768x24 &
install:  
  - mvn clean test
  - heroku maintenance:on --app gauge-example-reports
  - heroku git:clone -a gauge-example-reports
  - cd gauge-example-reports
  - mkdir -p groovy/public
  - cp -rf ../reports/html-report/* groovy/public
  - git add .
  - git commit -m "update Groovy reports for build ${TRAVIS_BUILD_NUMBER}"
  - git push heroku master
  - heroku maintenance:off --app gauge-example-reports